import {expect, test} from '@playwright/test';

test('simulated improvement review, stale approval, rejection, rollback and privacy controls', async ({page}) => {
  await page.setViewportSize({width: 1000, height: 760});
  await page.goto('/?onboarded=1&service=memory');
  await page.keyboard.press('Control+,');
  await page.getByRole('tab', {name: 'AgentGateway'}).click();
  await expect(page.getByText('Simulated development data')).toBeVisible();
  await expect(page.getByRole('switch', {name: 'Enable continual improvement'})).not.toBeChecked();
  await page.getByRole('switch', {name: 'Enable continual improvement'}).focus();
  await page.keyboard.press('Space');
  await page.getByRole('button', {name: 'Prepare improvement runtime'}).click();
  await page.getByRole('button', {name: 'Analyze improvement evidence'}).click();
  const candidate = page.getByRole('article', {name: 'Simulated clarification improvement'});
  await candidate.getByText('Review changes and measurements').click();
  await expect(candidate.getByText(/Ask for clarification/)).toBeVisible();
  await expect(candidate.getByRole('cell', {name: '1/3 → 3/3', exact: true})).toBeVisible();
  await page.getByRole('button', {name: 'Approve Simulated clarification improvement'}).click();
  await expect(page.getByText('Active version 1')).toBeVisible();
  await expect(page.getByRole('button', {name: 'Approve Simulated find, answer and draft workflow'})).toBeDisabled();
  const stale = page.getByRole('article', {name: 'Simulated find, answer and draft workflow'});
  await stale.getByText('Review changes and measurements').click();
  await expect(stale.getByText('Comparing against version 0')).toBeVisible();
  await expect(stale.getByText(/Before:\s*\[\]/)).toBeVisible();
  await page.getByRole('button', {name: 'Reject Simulated find, answer and draft workflow'}).click();
  await page.getByRole('button', {name: 'Roll back to version 0'}).click();
  await expect(page.getByText('Active version 0')).toBeVisible();
  await page.getByRole('tab', {name: 'Activity', exact: true}).click();
  await page.getByRole('switch', {name: 'Pause continual improvement'}).focus();
  await page.keyboard.press('Space');
  await expect(page.getByRole('switch', {name: 'Pause continual improvement'})).toBeChecked();
  await page.getByRole('tab', {name: 'Privacy'}).click();
  await page.getByRole('switch', {name: 'Improvement cloud consent'}).focus();
  await page.keyboard.press('Space');
  await expect(page.getByRole('switch', {name: 'Improvement cloud consent'})).toBeChecked();
  await page.getByRole('button', {name: /Answer language/}).click();
  await page.getByRole('option', {name: 'English'}).click();
  await page.getByRole('button', {name: 'Save answer language preference'}).click();
  await page.getByRole('button', {name: 'Delete improvement data', exact: true}).click();
  await page.getByRole('button', {name: 'Delete improvement data permanently'}).click();
  await expect(page.getByRole('switch', {name: 'Improvement cloud consent'})).not.toBeChecked();
  await page.getByRole('tab', {name: 'AgentGateway'}).click();
  await expect(page.getByRole('switch', {name: 'Enable continual improvement'})).not.toBeChecked();
  await expect(page.getByText('No candidates.', {exact: true})).toBeVisible();
});
